### PR TITLE
Removal ada_2_hl7 scripts

### PR DESCRIPTION
**Pull request by xatapult**
Because we're moving `HL7-mappings/ada_2_hl7` to YATC (`YATC-internal/ada-2-hl7`), all Ant scripts, stylesheets and batch/shell scripts are removed from `HL7-mappings/ada_2_hl7`.

### CODE REVIEW

**Comment by xatapult** [comment]
What strange entries?

**Comment by weteringac** [comment]
> What strange entries?

xml tag was hidden in my previous comment, I now removed the '<' so it is visible ;-)

**Comment by xatapult** [comment]
@weteringac De melding hierboven is wat incompleet. Ik neem aan dat je onderstaande bedoelt? Dat had je op een Teams chat gemeld:

```
<file name="file:/C:/SourceTree/GitHub/Nictiz/YATC-shared/xplmod/yatc-fast-transforms.mod.xpl"
            detection-count="1">
<fail>
<svrl:failed-assert role="fatal"
                                test="(processing error)"
                                xmlns:svrl="[http://purl.oclc.org/dsdl/svrl">Schematron](http://purl.oclc.org/dsdl/svrl%22%3ESchematron) processing error err:FORG0006: Effective boolean value is not defined for a sequence of two or more items starting with a boolean</svrl:failed-assert>
</fail>
</file>
```

**Review by ahenket — APPROVED** [review]
Ran all transforms and see no issues

**Pull request merged**
