### PR TITLE
MP-1223

### PR DESCRIPTION
**Pull request by weteringac**
Update for new xsd to allow for substanceAdministration FHIR Timing effectiveTime.
Add configurable schemaLocation attribute in xsl.

### CODE REVIEW

**Review by ahenket — CHANGES_REQUESTED** [review]
There are merge issues with master. Could you resolve those so we can close this one?

**Review by helmavdl — CHANGES_REQUESTED** [review]
I agree with Alexander

**Comment by weteringac** [comment]
> There are merge issues with master. Could you resolve those so we can close this one?

Done!

**Review by ahenket — CHANGES_REQUESTED** [review]
There no more conflicts but this PR would bring back many ant build files. I don't think that was the intention?

**Pull request merged**
